services:
  # Container Laravel (PHP 8.2 + Apache)
  bap-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bap-laravel
    ports:
      - "8080:80" # Akses web lewat port 8080 di browser
    volumes:
      - .:/var/www/html # Mirroring file dari laptop ke dalam kontainer
      - ./php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
    - bap-db
    networks:
      - bap-network
    restart: always

  # Container Database (MySQL 8.0)
  bap-db:
    image: mysql:8.0
    container_name: bap-mysql
    ports:
      - "4406:3306" # Agar tidak bentrok dengan MySQL XAMPP (3306)
    environment:
      MYSQL_DATABASE: db_bap
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      # (Opsional) Persist data database biar kalau container mati data ga ilang
      - db_data:/var/lib/mysql
    networks:
      - bap-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bap-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: bap-db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - bap-db
    networks:
      - bap-network
    restart: always

networks:
  bap-network:
    driver: bridge

volumes:
  db_data: